safe rollout

diff --git a/.github/workflows/auto_saferollout.yml b/.github/workflows/auto_saferollout.yml
--- a/.github/workflows/auto_saferollout.yml
+++ b/.github/workflows/auto_saferollout.yml
@@ -2,44 +2,44 @@ name: auto-saferollout
 on:
   workflow_dispatch:
   workflow_run:
-    workflows: ["register-model"]
+    workflows: ["train"]
     types: [completed]
 
 env:
   RC_DEPLOYMENT_NAME: run${{ github.run_number }}
   METRICS_VALIDATION_INTERVAL_MINS: 5
-  LOAD_GENERATOR_DURATION: 70m #minutes
+  LOAD_GENERATOR_DURATION: 30m
+  ENDPOINT_FILE: endpoint/endpoint.yml
+  DEPLOYMENT_FILE: endpoint/deployment.yml
   
 jobs:
   
-  rollout_10pct_traffic:
-    name: Rollout 10% traffic
+  create_rc_deployment:
+    name: Create new deployment(RC)
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'}}
-    steps:
-    - name: Configure endpoint files
-      run: |
-        echo "ENDPOINT_FILE=endpoint/endpoint.yml" >> $GITHUB_ENV
-        echo "DEPLOYMENT_FILE=endpoint/deployment.yml" >> $GITHUB_ENV
+    outputs:
+      NOT_FIRST_RUN: ${{ steps.create_initial_prod.outputs.NOT_FIRST_RUN }}
+    steps:    
     - name: Checkout
       uses: actions/checkout@v2.3.3
     - name: azure login
       uses: azure/login@v1
       with:
-        creds: ${{secrets.AZURE_TOKEN}}
+        creds: ${{secrets.AZURE_CREDENTIALS}}
     - name: Set defaults
       run: |
         az config set defaults.workspace=${{secrets.AML_WORKSPACE}}
         az config set defaults.group=${{secrets.RESOURCE_GROUP}}
         az account set -s ${{secrets.SUBSCRIPTION_ID}}  
     - name: Install azureml cli extension
-      run: az extension add -n ml -y
-    
+      run: az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.15_october_cand-py3-none-any.whl --yes
+            
     - name: Download latest model details
       uses: dawidd6/action-download-artifact@v2      
       with:
         name: latest-model
-        workflow: register_model.yml
+        workflow: train.yml
         #workflow_conclusion: success
     - name: Get latest model id
       run: |
@@ -47,52 +47,88 @@ jobs:
         echo "LATEST_MODEL=$LATEST_MODEL" >> $GITHUB_ENV
     # step 1: validation and day1 scenarios
     - name: Step 1a-If endpoint does not exist, create
-      run: |
-        export ENDPOINT_EXISTS=$(az ml endpoint list -o tsv --query "[?name=='${{secrets.ENDPOINT_NAME }}'][name]" |  wc -l)
+      run: |        
+        export ENDPOINT_EXISTS=$(az ml online-endpoint list -o tsv --query "[?name=='${{secrets.ENDPOINT_NAME }}'][name]" |  wc -l)
         if [[ ENDPOINT_EXISTS -ne 1 ]]; then
-          az ml endpoint create -n ${{secrets.ENDPOINT_NAME }} -f ${{ env.ENDPOINT_FILE }}
+          az ml online-endpoint create -n ${{secrets.ENDPOINT_NAME }} -f ${{ env.ENDPOINT_FILE }}          
         else
-          echo "endpoint ${{secrets.ENDPOINT_NAME }} exists"
-        fi
-
-    - name: Step 1b-validate new deployment name does not exiat
-      run: |
-        export RC_DEPLOYMENT_EXISTS=$(az ml endpoint show -n ${{secrets.ENDPOINT_NAME }} -o tsv --query "deployments[?name == '${{ env.RC_DEPLOYMENT_NAME }}'].name" |  wc -l)
-        if [[ RC_DEPLOYMENT_EXISTS -eq 1 ]]; then
-        echo "deployment with name ${{ env.RC_DEPLOYMENT_NAME }} already exists. Exiting."
-        exit 1
+          echo "endpoint exists"
         fi
     
-      # Step 1c - If prod does not exist, create the RC as prod. Else If PROD exists validate if it has 100%.
-    - name: Step 1c-if PROD does not exist, create RC as PROD
-      run: |
-        # get number of deployments
-        export NUM_DEPLOYMENTS=$(az ml endpoint show -n ${{secrets.ENDPOINT_NAME }} -o tsv --query 'deployments | length(@)' | tr -d "\r")
-        echo "NUM_DEPLOYMENTS=$NUM_DEPLOYMENTS" >> $GITHUB_ENV
-        # This below limitation will go with GA release
-        if [[ $NUM_DEPLOYMENTS -gt '1' ]]; then echo "Error: Only one deployment (PROD) can exist"; exit 1; fi
+    # Step 1b - If prod does not exist, create the RC as prod. Else If PROD exists validate if it has 100%.
+    - id: create_initial_prod
+      name: Step 1c-if PROD does not exist, create RC as PROD              
+      run: |        
         # Get the name of prod deployment
-        export PROD_DEPLOYMENT=$(az ml endpoint show -n ${{secrets.ENDPOINT_NAME }} -o tsv --query "tags.PROD_DEPLOYMENT")
+        export PROD_DEPLOYMENT=$(az ml online-endpoint show -n ${{secrets.ENDPOINT_NAME }} -o tsv --query "tags.PROD_DEPLOYMENT")
+        
         echo "PROD_DEPLOYMENT=$PROD_DEPLOYMENT" >> $GITHUB_ENV
         if [[ -z "$PROD_DEPLOYMENT" ]]; then
-          export PROD_DEPLOYMENT=${{ env.RC_DEPLOYMENT_NAME }}  
-          az ml endpoint update -n ${{secrets.ENDPOINT_NAME }} --deployment $PROD_DEPLOYMENT --deployment-file ${{ env.DEPLOYMENT_FILE }} --set deployments[$NUM_DEPLOYMENTS].model=${{ env.LATEST_MODEL }} --traffic $PROD_DEPLOYMENT:100 --set tags.PROD_DEPLOYMENT=$PROD_DEPLOYMENT
-          # github action does not allow with exit 0.
-          exit 1
+          echo "prod deployment does not exist - creating it"
+          export PROD_DEPLOYMENT=${{ env.RC_DEPLOYMENT_NAME }}
+          az ml online-deployment create --name ${{ env.RC_DEPLOYMENT_NAME }} --endpoint ${{secrets.ENDPOINT_NAME }} -f ${{ env.DEPLOYMENT_FILE }} --all-traffic --set model=${{ env.LATEST_MODEL }}
+          az ml online-endpoint update --name ${{secrets.ENDPOINT_NAME }} --set tags.PROD_DEPLOYMENT=$PROD_DEPLOYMENT                    
         else # validate if PROD  has 100%.
-          export PROD_TRAFFIC=$(az ml endpoint show -n ${{secrets.ENDPOINT_NAME }} -o tsv --query traffic.$PROD_DEPLOYMENT)
-          if [[ $PROD_TRAFFIC -ne '100' ]]; then echo "Error: traffic to prod deployment needs to be 100%"; exit 1; fi   
+          echo "validating if prod as 100%"
+          export PROD_TRAFFIC=$(az ml online-endpoint show -n ${{secrets.ENDPOINT_NAME }} -o tsv --query traffic.$PROD_DEPLOYMENT)
+          if [[ $PROD_TRAFFIC -ne '100' ]]; then echo "Error: For this saferollout script to start, traffic to prod deployment needs to be 100%"; exit 1; fi  
+
+          echo "::set-output name=NOT_FIRST_RUN::true"
+          echo "NOT_FIRST_RUN=true" >> $GITHUB_ENV
         fi
     - name: Step 2-Create RC deployment
+      if: ${{ env.NOT_FIRST_RUN }}
       run: |          
-        az ml endpoint update -n ${{secrets.ENDPOINT_NAME }} --deployment ${{ env.RC_DEPLOYMENT_NAME }} --deployment-file ${{ env.DEPLOYMENT_FILE }} --set deployments[${{ env.NUM_DEPLOYMENTS }}].model=${{ env.LATEST_MODEL }} --traffic "${{ env.PROD_DEPLOYMENT }}:100,${{ env.RC_DEPLOYMENT_NAME }}:0"
- 
+        az ml online-deployment create --name ${{ env.RC_DEPLOYMENT_NAME }} --endpoint ${{secrets.ENDPOINT_NAME }} -f ${{ env.DEPLOYMENT_FILE }} --all-traffic --set model=${{ env.LATEST_MODEL }}
+
+  sanity_test_0pct_traffic:
+    needs: [create_rc_deployment]    
+    name: Sanity test without live traffic
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v2.3.3
+    - name: azure login
+      uses: azure/login@v1
+      with:
+        creds: ${{secrets.AZURE_CREDENTIALS}}
+    - name: Set defaults
+      run: |
+        az config set defaults.workspace=${{secrets.AML_WORKSPACE}}
+        az config set defaults.group=${{secrets.RESOURCE_GROUP}}
+        az account set -s ${{secrets.SUBSCRIPTION_ID}}  
+    - name: Install azureml cli extension
+      run: az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.15_october_cand-py3-none-any.whl --yes
+    - name: Step 3-Sanity test RC with zero traffic      
+      run: |          
+        az ml online-endpoint invoke -n ${{secrets.ENDPOINT_NAME }} --deployment ${{ env.RC_DEPLOYMENT_NAME }} --request-file endpoint/sample-request.json
+
+  rollout_10pct_traffic:
+    needs: [sanity_test_0pct_traffic]
+    if: ${{ needs.create_rc_deployment.outputs.NOT_FIRST_RUN }}
+    name: Rollout 10% traffic
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v2.3.3
+    - name: azure login
+      uses: azure/login@v1
+      with:
+        creds: ${{secrets.AZURE_CREDENTIALS}}
+    - name: Set defaults
+      run: |
+        az config set defaults.workspace=${{secrets.AML_WORKSPACE}}
+        az config set defaults.group=${{secrets.RESOURCE_GROUP}}
+        az account set -s ${{secrets.SUBSCRIPTION_ID}}  
+    - name: Install azureml cli extension
+      run: az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.15_october_cand-py3-none-any.whl --yes
     - name: Step 3-Divert 10% traffic to RC
       run: | 
-        az ml endpoint update -n ${{secrets.ENDPOINT_NAME }} --traffic ${{ env.PROD_DEPLOYMENT }}:90,${{ env.RC_DEPLOYMENT_NAME }}:10
+          export PROD_DEPLOYMENT=$(az ml online-endpoint show -n ${{secrets.ENDPOINT_NAME }} -o tsv --query "tags.PROD_DEPLOYMENT")
+          az ml online-endpoint update -n ${{secrets.ENDPOINT_NAME }} --traffic "$PROD_DEPLOYMENT=90 ${{env.RC_DEPLOYMENT_NAME}}=10"        
 
   rollout_50pct_traffic:
-    needs: [validate_errors_within_threshold_10pct_traffic, validate_latency_within_threshold_10pct_traffic]
+    needs: [rollout_10pct_traffic, validate_errors_within_threshold_10pct_traffic, validate_latency_within_threshold_10pct_traffic]    
     name: Rollout 50% traffic    
     runs-on: ubuntu-latest
     steps:
@@ -101,20 +137,19 @@ jobs:
       - name: azure login
         uses: azure/login@v1
         with:
-          creds: ${{secrets.AZURE_TOKEN}}
+          creds: ${{secrets.AZURE_CREDENTIALS}}
       - name: Set defaults
         run: |
           az config set defaults.workspace=${{secrets.AML_WORKSPACE}}
           az config set defaults.group=${{secrets.RESOURCE_GROUP}}
-          az account set -s ${{secrets.SUBSCRIPTION_ID}}
-      
+          az account set -s ${{secrets.SUBSCRIPTION_ID}}      
       
       - name: Install azureml cli extension
-        run: az extension add -n ml -y
+        run: az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.15_october_cand-py3-none-any.whl --yes
       - name: Divert 50% traffic to RC
         run: | 
-          export PROD_DEPLOYMENT=$(az ml endpoint show -n ${{secrets.ENDPOINT_NAME }} -o tsv --query "tags.PROD_DEPLOYMENT")          
-          az ml endpoint update -n ${{secrets.ENDPOINT_NAME }} --traffic $PROD_DEPLOYMENT:50,${{ env.RC_DEPLOYMENT_NAME }}:50
+          export PROD_DEPLOYMENT=$(az ml online-endpoint show -n ${{secrets.ENDPOINT_NAME }} -o tsv --query "tags.PROD_DEPLOYMENT")
+          az ml online-endpoint update -n ${{secrets.ENDPOINT_NAME }} --traffic "$PROD_DEPLOYMENT=50 ${{env.RC_DEPLOYMENT_NAME}}=50"
 
   rollout_100pct_traffic:
     needs: [validate_errors_within_threshold_50pct_traffic, validate_latency_within_threshold_50pct_traffic]
@@ -126,18 +161,18 @@ jobs:
       - name: azure login
         uses: azure/login@v1
         with:
-          creds: ${{secrets.AZURE_TOKEN}}
+          creds: ${{secrets.AZURE_CREDENTIALS}}
       - name: Set defaults
         run: |
           az config set defaults.workspace=${{secrets.AML_WORKSPACE}}
           az config set defaults.group=${{secrets.RESOURCE_GROUP}}
           az account set -s ${{secrets.SUBSCRIPTION_ID}}
       - name: Install azureml cli extension
-        run: az extension add -n ml -y
+        run: az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.15_october_cand-py3-none-any.whl --yes
       - name: Divert 100% traffic to RC and mark RC as PROD, PROD as OLD_PROD
         run: | 
-          export PROD_DEPLOYMENT=$(az ml endpoint show -n ${{secrets.ENDPOINT_NAME }} -o tsv --query "tags.PROD_DEPLOYMENT")          
-          az ml endpoint update -n ${{secrets.ENDPOINT_NAME }} --traffic $PROD_DEPLOYMENT:0,${{ env.RC_DEPLOYMENT_NAME }}:100 --set tags.PROD_DEPLOYMENT=${{ env.RC_DEPLOYMENT_NAME }} tags.OLD_PROD_DEPLOYMENT=$PROD_DEPLOYMENT
+          export PROD_DEPLOYMENT=$(az ml online-endpoint show -n ${{secrets.ENDPOINT_NAME }} -o tsv --query "tags.PROD_DEPLOYMENT")          
+          az ml online-endpoint update -n ${{secrets.ENDPOINT_NAME }} --traffic "${{env.RC_DEPLOYMENT_NAME}}=100" --set tags.PROD_DEPLOYMENT=${{ env.RC_DEPLOYMENT_NAME }} tags.OLD_PROD_DEPLOYMENT=$PROD_DEPLOYMENT
 
   delete_old_prod:
     needs: [validate_errors_within_threshold_100pct_traffic, validate_latency_within_threshold_100pct_traffic]
@@ -149,26 +184,25 @@ jobs:
       - name: azure login
         uses: azure/login@v1
         with:
-          creds: ${{secrets.AZURE_TOKEN}}
+          creds: ${{secrets.AZURE_CREDENTIALS}}
       - name: Set defaults
         run: |
           az config set defaults.workspace=${{secrets.AML_WORKSPACE}}
           az config set defaults.group=${{secrets.RESOURCE_GROUP}}
           az account set -s ${{secrets.SUBSCRIPTION_ID}}
       - name: Install azureml cli extension
-        run: az extension add -n ml -y
+        run: az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.15_october_cand-py3-none-any.whl --yes
       - name: Divert 100% traffic to RC and mark RC as PROD, PROD as OLD_PROD
         run: | 
-          export OLD_PROD_DEPLOYMENT=$(az ml endpoint show -n ${{secrets.ENDPOINT_NAME }} -o tsv --query "tags.OLD_PROD_DEPLOYMENT")          
-          az ml endpoint delete -n ${{secrets.ENDPOINT_NAME }} --deployment $OLD_PROD_DEPLOYMENT --yes #--no-wait
-          az ml endpoint update -n ${{secrets.ENDPOINT_NAME }} --remove tags.OLD_PROD_DEPLOYMENT
+          export OLD_PROD_DEPLOYMENT=$(az ml online-endpoint show -n ${{secrets.ENDPOINT_NAME }} -o tsv --query "tags.OLD_PROD_DEPLOYMENT")          
+          az ml online-endpoint update -n ${{secrets.ENDPOINT_NAME }} --remove tags.OLD_PROD_DEPLOYMENT
+          az ml online-deployment delete --endpoint ${{secrets.ENDPOINT_NAME }} --name $OLD_PROD_DEPLOYMENT --yes --no-wait          
 
   ############## auto validation of metrics ################
   validate_errors_within_threshold_10pct_traffic:
     needs: rollout_10pct_traffic
     name: Validate errors within threshold @ 10% traffic
-    environment:
-      name: auto_rollout_50pct_traffic
+    environment: auto_rollout_50pct_traffic
     runs-on: ubuntu-latest
     steps:
       - run: |
@@ -190,7 +224,7 @@ jobs:
           threshold: 1
           resource_id: ${{ env.RESOURCE_ID }}
         env:
-          AZURE_CREDENTIALS: ${{secrets.AZURE_TOKEN}}
+          AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
       # Upload the chart as an artifact to the workflow run
       - uses: actions/upload-artifact@v2
         with:
@@ -200,8 +234,7 @@ jobs:
   validate_errors_within_threshold_50pct_traffic:
     needs: rollout_50pct_traffic
     name: Validate errors within threshold @ 50% traffic
-    environment:
-      name: auto_rollout_100pct_traffic
+    environment: auto_rollout_100pct_traffic
     runs-on: ubuntu-latest
     steps:
       - run: |
@@ -223,7 +256,7 @@ jobs:
           threshold: 0
           resource_id: ${{ env.RESOURCE_ID }}
         env:
-          AZURE_CREDENTIALS: ${{secrets.AZURE_TOKEN}}
+          AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
       # Upload the chart as an artifact to the workflow run
       - uses: actions/upload-artifact@v2
         with:
@@ -233,8 +266,7 @@ jobs:
   validate_errors_within_threshold_100pct_traffic:
     needs: rollout_100pct_traffic
     name: Validate errors within threshold @ 100% traffic
-    environment:
-      name: auto_delete_old_prod
+    environment: delete_old_prod_env
     runs-on: ubuntu-latest
     steps:
       - run: |
@@ -256,7 +288,7 @@ jobs:
           threshold: 0
           resource_id: ${{ env.RESOURCE_ID }}
         env:
-          AZURE_CREDENTIALS: ${{secrets.AZURE_TOKEN}}
+          AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
       # Upload the chart as an artifact to the workflow run
       - uses: actions/upload-artifact@v2
         with:
@@ -266,8 +298,7 @@ jobs:
 
   validate_latency_within_threshold_10pct_traffic:
     needs: rollout_10pct_traffic
-    environment:
-      name: auto_rollout_50pct_traffic
+    environment: rollout_50pct_traffic_env
     name: Validate latency within threshold @ 10% traffic
     runs-on: ubuntu-latest
     steps:
@@ -290,7 +321,7 @@ jobs:
           threshold: 50
           resource_id: ${{ env.RESOURCE_ID }}
         env:
-          AZURE_CREDENTIALS: ${{secrets.AZURE_TOKEN}}
+          AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
       # Upload the chart as an artifact to the workflow run
       - uses: actions/upload-artifact@v2
         with:
@@ -300,7 +331,7 @@ jobs:
   validate_latency_within_threshold_50pct_traffic:
     needs: rollout_50pct_traffic
     environment:
-      name: auto_rollout_100pct_traffic
+      name: rollout_100pct_traffic_env
     name: Validate latency within threshold @ 50% traffic
     runs-on: ubuntu-latest
     steps:
@@ -323,7 +354,7 @@ jobs:
           threshold: 50
           resource_id: ${{ env.RESOURCE_ID }}
         env:
-          AZURE_CREDENTIALS: ${{secrets.AZURE_TOKEN}}
+          AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
       # Upload the chart as an artifact to the workflow run
       - uses: actions/upload-artifact@v2
         with:
@@ -356,7 +387,7 @@ jobs:
           threshold: 50
           resource_id: ${{ env.RESOURCE_ID }}
         env:
-          AZURE_CREDENTIALS: ${{secrets.AZURE_TOKEN}}
+          AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
       # Upload the chart as an artifact to the workflow run
       - uses: actions/upload-artifact@v2
         with:
@@ -370,11 +401,11 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2.3.3
       - name: Install azureml cli extension
-        run: az extension add -n ml -y
+        run: az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.15_october_cand-py3-none-any.whl --yes
       - name: azure login
         uses: azure/login@v1
         with:
-          creds: ${{secrets.AZURE_TOKEN}}
+          creds: ${{secrets.AZURE_CREDENTIALS}}
       - name: Set defaults
         run: |
           az config set defaults.workspace=${{secrets.AML_WORKSPACE}}
@@ -387,7 +418,14 @@ jobs:
           tar -xvf vegeta_12.8.4_linux_amd64.tar.gz
       - name: "Open live traffic"
         run: |
-          ENDPOINT_URI=$(az ml endpoint show -n ${{secrets.ENDPOINT_NAME}} -o tsv --query scoring_uri)        
+          export ENDPOINT_EXISTS=$(az ml online-endpoint list -o tsv --query "[?name=='${{secrets.ENDPOINT_NAME }}'][name]" |  wc -l)
+          if [[ ENDPOINT_EXISTS -ne 1 ]]; then echo "Endpoint does not exist. Maybe initial run?"; exit 0; fi          
+          ENDPOINT_URI=$(az ml online-endpoint show -n ${{secrets.ENDPOINT_NAME}} -o tsv --query scoring_uri)        
           echo $ENDPOINT_URI
-          ENDPOINT_TOKEN=$(az ml endpoint get-credentials -n ${{secrets.ENDPOINT_NAME}} -o tsv --query primaryKey)
-          echo "POST $ENDPOINT_URI" | ./vegeta attack -body test/sample-request.json -header "Content-Type: application/json" -header "authorization: Bearer $ENDPOINT_TOKEN" -rate=15 -duration ${{env.LOAD_GENERATOR_DURATION}} -output loadtest.out 
+          ENDPOINT_TOKEN=$(az ml online-endpoint get-credentials -n ${{secrets.ENDPOINT_NAME}} -o tsv --query primaryKey)
+          echo "POST $ENDPOINT_URI" | ./vegeta attack -body endpoint/sample-request.json -header "Content-Type: application/json" -header "authorization: Bearer $ENDPOINT_TOKEN" -rate=15 -duration ${{env.LOAD_GENERATOR_DURATION}} | ./vegeta report --type=text > traffic_report.txt
+          cat traffic_report.txt
+      - uses: actions/upload-artifact@v2
+        with:
+          name: load-generator-traffic-report
+          path: "traffic_report.txt"
