fix

diff --git a/.github/workflows/saferollout.yml b/.github/workflows/saferollout.yml
--- a/.github/workflows/saferollout.yml
+++ b/.github/workflows/saferollout.yml
@@ -74,6 +74,7 @@ jobs:
         # get number of deployments
         export NUM_DEPLOYMENTS=$(az ml endpoint show -n ${{ github.event.inputs.endpoint_name }} -o tsv --query 'deployments | length(@)' | tr -d "\r")
         echo "NUM_DEPLOYMENTS=$NUM_DEPLOYMENTS" >> $GITHUB_ENV
+        if [[ $NUM_DEPLOYMENTS -gt '1' ]]; then echo "Error: one deployment (PROD) can exist"; exit 1; fi
         # Get the name of prod deployment
         export PROD_DEPLOYMENT=$(az ml endpoint show -n ${{ github.event.inputs.endpoint_name }} -o tsv --query "tags.PROD_DEPLOYMENT")
         echo "PROD_DEPLOYMENT=$PROD_DEPLOYMENT" >> $GITHUB_ENV
